# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - agenthubtest

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout Github Action' 
        uses: actions/checkout@master
  
      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: 'npm install, build, and test'
        run: |
          npm install
          npm run build --if-present
          npm run start --if-present
  
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'agenthubtest'
          slot-name: 'Production'
          clean: true
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D7C0BBC22CD541899821F08A9F00B4B2 }}
          package: .
